model_type: yolov8n.pt
pretrained: True
seed: 0
imgsz: 640 
batch: 8 
epochs: 2
optimizer: Adam # other choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
lr0: 0.001  # learning rate 
name: 'yolov8s_exp_v2' # experiment name
