model_type: yolov8s.pt
pretrained: True
seed: 0
imgsz: 640 
batch: 8 
epochs: 5
optimizer: Adam # other choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
lr0: 0.001  # learning rate 
name: 'yolov8s_exp_v1' # experiment name
